### ISSUE TITLE
API version 9.74 AttributeError

### ISSUE THREAD

**Issue by jakezimmerman22** [quantrocket-llc/ibpythonic#4] opened 2018-11-30 22:08 UTC
I have only seen this with API version 9.74. Below is the first half of the quickstart provided. Imports are fine. The error occurs when trying to connect...

from ibpythonic import ibConnection, message
from ibapi.contract import Contract

def contractDetailsHandler(msg):
    print(msg.contractDetails)
    # do something with contractDetails msg

def errorHandler(msg):
    print(msg)

conn = ibConnection(port=4001, clientId=100)   --> *ERROR*

>>>
Traceback (most recent call last):
  File "C:/TWS API/source/pythonclient/pythonic_test.py", line 11, in <module>
    conn = ibConnection(port=4001, clientId=100)
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python37\lib\site-packages\ibpythonic\connection.py", line 88, in create
    receiver = Receiver(dispatcher) if receiver is None else receiver
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python37\lib\site-packages\ibpythonic\receiver.py", line 26, in dispatchMethod
    self.dispatcher(name, dict(list(zip(parameters, arguments))))
AttributeError: 'Receiver' object has no attribute 'dispatcher'
>>>

**Comment by misantroop** [comment] 2018-12-01 11:08
Exactly the same error here. Logging in 9.74 seems to be very different, which is most likely the cause.

**Comment by brian-from-quantrocket** [comment] 2018-12-03 14:18
QuantRocket is currently pinned to 9.73 so haven't encountered this error yet. Will look at it when I get a moment.

**Comment by brian-from-quantrocket** [comment] 2018-12-05 20:11
IB added an `__init__` method to the EWrapper class which caused a name collision. This is fixed in 0.1.5:

    pip install -U ibpythonic

**Closed as completed by brian-from-quantrocket** 2018-12-05 20:11 UTC

**Comment by misantroop** [comment] 2018-12-06 11:08
Much appreciated.

**Comment by jakezimmerman22** [comment] 2018-12-06 14:08
Thanks Brian.
